### ISSUE TITLE
Overnight events aren't counted

### ISSUE THREAD

**Issue by tertiumsquid** [aronwoost/google-calendar-hours#27] opened 2016-08-26 04:34 UTC
Overnight events (or more specifically, events that cross from one time period to the next) are not counted.

For example, there's an event in my calendar that started on Saturday and ended on Sunday.  That event is not counted by the Google Calendar Hours Calculator for either last week or this week.  Same thing if I have it calculate daily or monthly events; anything that crosses from one day or month to the next doesn't show on either the day it starts or the day it ends.

**Comment by dfsklar** [comment] 2016-10-11 23:52
Similarly: full-day events are not counted and that's a problem for me.  I sometimes need to consider a full-day event as counting for 8 hours.  It would be nice to provide a UI allowing the user to select one of two ways to handle full-day events:
1) Ignore
2) Consider each full-day event to be ______ hour(s)

**Comment by dereknheiley** [comment] 2016-10-31 13:11
the problem is, there are multiple ways to solve this problem

a) count all event time in the day the event started
b) count all event time in the day the event ended
c) divide event time into portions so that time until 12am is recorded on day i, and time after 12am is recorded on day i+1

Each has their own merit for certain users
a) might be what most night owls would expect, but if you started work at 11:30pm and ended at 4am b) would make more logical sense
c) would be the most accurate depiction of what actually happened, especially if you had an event starting at 6pm on one day, and ended at 10am two days later, similar to defining a week start and end day, you could potentially allow users to specify roll over time of 3am or something.

c) is also the most challenging to implement since you theoreticaly have to handle cases where an event started in the distant past, and keeps going into the distant future. i'm not sure how the google api's allow for capturing time from such an event, if at all

the simplest solution might be allowing users to specify their own day end time and not worry about edge cases like multi-day events

**Comment by voarsh** [comment] 2018-01-25 02:17
This needs to be sorted! Not sure if this project is dead. Someone needs to fork it and FIX this issue.

**Comment by vickesh** [comment] 2020-02-12 17:21
wouldd like to see dfsklar  suggestion implemented

**Comment by aronwoost** [comment] 2021-04-22 18:12
Overnight events has been fixed with #138.

Note that full-day events are still not counted. This is by design.

**Closed by aronwoost** 2021-04-22 18:12 UTC
