### ISSUE TITLE
Will not calculate past 365 days from current date

### ISSUE THREAD

**Issue by beetlelea** [aronwoost/google-calendar-hours#144] opened 2021-07-16 19:19 UTC
**First.... this is awesome!!** I've searched and searched for something like this and you've saved my sanity!

Second. I create yearly calendars for our nursing program (Jan - Dec). They must be finalized by Sept of the prior year. When calculating the calendar for the upcoming 2022 calendar year, the _google-calendar-hours_ code stops calculating at 365 days past the current date. Is it possible to make coding changes for that calculation?

Thanks again for everything! I love this!

**Comment by aronwoost** [comment] 2021-07-16 20:06
Duplicate of #142

**Closed by aronwoost** 2021-07-16 20:06 UTC

**Comment by beetlelea** [comment] 2021-07-16 20:25
I will check but it may be Monday. I literally just left the school. This is an awesome app!!

On Jul 16, 2021, at 3:06 PM, Aron Woost ***@***.***> wrote:

﻿
Closed #144.

**Comment by beetlelea** [comment] 2021-07-19 17:27
Awesome! It works! Thanks so much
